### ISSUE TITLE
Module doesn't work on iOS, build fails

### ISSUE THREAD

**Issue by arifje** [leandromacrini/fci1908#1]
SDK 3.4.1.GA, iOS

[ERROR] :  *\* BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/Debug-iphonesimulator/MyApp.app/MyApp normal i386
[ERROR] :  (1 failure)

**Comment by leandromacrini** [comment]
Not a Ti.Admob error
